import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import { toWIB, nowWIB } from '@/lib/timezone';

const prisma = new PrismaClient();

// GET - Get agent dashboard data
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const agentId = searchParams.get('agentId');

    if (!agentId) {
      return NextResponse.json(
        { error: 'Agent ID is required' },
        { status: 400 }
      );
    }

    // Get agent
    const agent = await prisma.agent.findUnique({
      where: { id: agentId },
    });

    if (!agent) {
      return NextResponse.json({ error: 'Agent not found' }, { status: 404 });
    }

    // Get all vouchers generated by this agent (using batch code pattern)
    const agentBatchPattern = agent.name.toUpperCase().replace(/[^A-Z0-9]/g, '');
    const allVouchers = await prisma.hotspotVoucher.findMany({
      where: {
        batchCode: {
          startsWith: agentBatchPattern,
        },
      },
      include: {
        profile: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    // Calculate statistics from AgentSale table (same as admin page)
    // Use WIB timezone for month calculation (UTC stored in DB)
    const now = nowWIB();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    const allSales = await prisma.agentSale.findMany({
      where: {
        agentId: agent.id,
      },
    });

    // Current month sales - Convert UTC to WIB before comparison
    const currentMonthSales = allSales.filter((sale) => {
      const saleDate = toWIB(sale.createdAt);
      if (!saleDate) return false;
      return (
        saleDate.getMonth() === currentMonth &&
        saleDate.getFullYear() === currentYear
      );
    });

    const stats = {
      currentMonth: {
        total: currentMonthSales.reduce((sum, sale) => sum + sale.amount, 0),
        count: currentMonthSales.length,
      },
      allTime: {
        total: allSales.reduce((sum, sale) => sum + sale.amount, 0),
        count: allSales.length,
      },
      generated: allVouchers.length,
      waiting: allVouchers.filter((v) => v.status === 'WAITING').length,
    };

    // Get profiles with agentAccess enabled
    const profiles = await prisma.hotspotProfile.findMany({
      where: {
        agentAccess: true,
        isActive: true,
      },
      orderBy: { name: 'asc' },
    });

    return NextResponse.json({
      agent: {
        id: agent.id,
        name: agent.name,
        phone: agent.phone,
        email: agent.email,
      },
      stats,
      profiles,
      vouchers: allVouchers.map((v) => ({
        id: v.id,
        code: v.code,
        batchCode: v.batchCode,
        status: v.status,
        profileName: v.profile?.name || 'Unknown',
        firstLoginAt: v.firstLoginAt,
        expiresAt: v.expiresAt,
        createdAt: v.createdAt,
      })),
    });
  } catch (error) {
    console.error('Get agent dashboard error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
